{"name": "Проверка неуспешного создания пользователя дважды", "status": "passed", "description": "Тест проверяет, что нельзя создать пользователя с уже существующими учётными данными.", "start": 1732589273199, "stop": 1732589273603, "uuid": "50fddc8f-13cc-4acc-99e6-67222f7519d4", "historyId": "70b00e187b151b9c9d67bb79a6d2a254", "testCaseId": "70b00e187b151b9c9d67bb79a6d2a254", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_twice_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "192.168.1.40"}, {"name": "thread", "value": "19334-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}